import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>🐱‍💻 Frontendmentor Repo</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
        👋  Greetings!!!  
        </h1>

        <p className={styles.description}>
          This is the collection of Frontendmentor Solutions....
        </p>


        <div className={styles.grid}>
          <Link href="/signup">
          <a  className={styles.card}>
            <h2>Sign Up Form</h2>
            <p>Simple Form Using React Hook Form.</p>
          </a>
          </Link>

          <Link href="/urlshort">
          <a className={styles.card}>
            <h2>URL shortening </h2>
            <p>Integrated with shrtcode URL shortening API with browser storage in the page</p>
          </a>
          </Link>

          
          <Link href="/spacetour">
          <a className={styles.card}>
            <h2>Space Tourism Website</h2>
            <p>Multipage website using local data.json file for different page data</p>
          </a>
          </Link>

          <Link href="/intcommsec">
          <a className={styles.card}>
            <h2>Interactive Comments section</h2>
            <p>Interactive Comments section and authentication page</p>
          </a>
          </Link>

          <Link href="/entertainweb">
          <a className={styles.card}>
            <h2>Entertainment Web App </h2>
            <p>Webpage using tmdb API with search functionality and state managemant</p>
          </a>
          </Link>

          <Link href="/countriesgame">
          <a className={styles.card}>
            <h2>Countries Games Page</h2>
            <p>Page with Light and Dark Mode.</p>
          </a>
          </Link>

          
         
        </div>
      </main>

      <footer className={styles.footer}>
          <h3>Created with ❤️ by Anju Soren</h3>   
              
      </footer> 
    </div>
  )
}
